# Generated by Django 5.0.3 on 2024-03-14 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0002_profile_date_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='follow',
            new_name='follows',
        ),
    ]
