# Generated by Django 5.0.4 on 2024-04-19 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musker', '0007_profile_facebook_link_profile_homapage_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='homapage_link',
            new_name='homepage_link',
        ),
    ]
